In [1]:
import numpy as np
import pandas as pd
import pprint
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
%matplotlib inline

In [2]:
iris = load_iris()

In [3]:
iris_df = pd.DataFrame(iris.data,columns=[iris.feature_names])

In [4]:
iris_df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm)
0               5.1              3.5               1.4              0.2
1               4.9              3.0               1.4              0.2
2               4.7              3.2               1.3              0.2
3               4.6              3.1               1.5              0.2
4               5.0              3.6               1.4              0.2

In [5]:
iris_df.shape

(150, 4)

In [6]:
from sklearn.preprocessing import StandardScaler
#Covert data into standard normal distribution
X = iris.data
X_std = StandardScaler().fit_transform(X)
print(X_std[0:15])


[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]
 [-0.53717756  1.93979142 -1.16971425 -1.05217993]
 [-1.50652052  0.78880759 -1.34022653 -1.18381211]
 [-1.02184904  0.78880759 -1.2833891  -1.3154443 ]
 [-1.74885626 -0.36217625 -1.34022653 -1.3154443 ]
 [-1.14301691  0.09821729 -1.2833891  -1.44707648]
 [-0.53717756  1.47939788 -1.2833891  -1.3154443 ]
 [-1.26418478  0.78880759 -1.22655167 -1.3154443 ]
 [-1.26418478 -0.13197948 -1.34022653 -1.44707648]
 [-1.87002413 -0.13197948 -1.51073881 -1.44707648]
 [-0.05250608  2.16998818 -1.45390138 -1.3154443 ]]


In [7]:
print("The shape of Feature Matrix is -",X_std.shape)

The shape of Feature Matrix is - (150, 4)


In [8]:
X_covariance_matrix = np.cov(X_std.T)

In [9]:
X_covariance_matrix

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [11]:
#Compute the eigenvalues and right eigenvectors using np.linalg.eig

eig_vals, eig_vecs = np.linalg.eig(X_covariance_matrix)

In [12]:
print('Eigenvectors \n%s' %eig_vecs)

Eigenvectors 
[[ 0.52106591 -0.37741762 -0.71956635  0.26128628]
 [-0.26934744 -0.92329566  0.24438178 -0.12350962]
 [ 0.5804131  -0.02449161  0.14212637 -0.80144925]
 [ 0.56485654 -0.06694199  0.63427274  0.52359713]]


In [13]:
print('\nEigenvalues \n%s' %eig_vals)


Eigenvalues 
[2.93808505 0.9201649  0.14774182 0.02085386]


In [14]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [15]:
# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [16]:
#In Python, lambda is a keyword used to define anonymous functions(functions with no name) 
#and that's why they are known as lambda functions

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
2.9380850501999936
0.920164904162487
0.14774182104494776
0.02085386217646217


In [17]:
tot = sum(eig_vals)

var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
print("Variance captured by each component is \n",var_exp)

Variance captured by each component is 
 [72.96244541329987, 22.850761786701774, 3.6689218892828714, 0.5178709107154775]


In [18]:
cum_var_exp = np.cumsum(var_exp)
print ("Cumulative variance captured as we travel each component \n",cum_var_exp)

Cumulative variance captured as we travel each component 
 [ 72.96244541  95.8132072   99.48212909 100.        ]


In [19]:
print("All Eigen Values along with Eigen Vectors")

print(eig_pairs)


All Eigen Values along with Eigen Vectors
[(2.9380850501999936, array([ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654])), (0.920164904162487, array([-0.37741762, -0.92329566, -0.02449161, -0.06694199])), (0.14774182104494776, array([-0.71956635,  0.24438178,  0.14212637,  0.63427274])), (0.02085386217646217, array([ 0.26128628, -0.12350962, -0.80144925,  0.52359713]))]


In [ ]:
#LAB ASSIGMENT

In [ ]:
#LAB ASSIGMENT: Find a CSV file online and work on it

In [10]:
a = pd.read_csv('car.csv')

In [11]:
a.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [12]:
a.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [13]:
a.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [14]:
a.shape

(301, 9)

In [15]:
a.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [16]:
a1 = a.drop('Car_Name',axis=1)
a2 = a1.drop('Fuel_Type',axis=1)
a3 = a2.drop('Seller_Type',axis=1)
a4 = a3.drop('Transmission',axis=1)


In [17]:
a4.head()

Year  Selling_Price  Present_Price  Kms_Driven  Owner
0  2014           3.35           5.59       27000      0
1  2013           4.75           9.54       43000      0
2  2017           7.25           9.85        6900      0
3  2011           2.85           4.15        5200      0
4  2014           4.60           6.87       42450      0

In [18]:
a4.describe()

Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [19]:
X = a4


In [20]:
print(X)

     Year  Selling_Price  Present_Price  Kms_Driven  Owner
0    2014           3.35           5.59       27000      0
1    2013           4.75           9.54       43000      0
2    2017           7.25           9.85        6900      0
3    2011           2.85           4.15        5200      0
4    2014           4.60           6.87       42450      0
..    ...            ...            ...         ...    ...
296  2016           9.50          11.60       33988      0
297  2015           4.00           5.90       60000      0
298  2009           3.35          11.00       87934      0
299  2017          11.50          12.50        9000      0
300  2016           5.30           5.90        5464      0

[301 rows x 5 columns]


In [21]:
X_std = StandardScaler().fit_transform(X)

In [22]:
print(X_std[0:15])

[[ 0.128897   -0.25841591 -0.23621461 -0.25622446 -0.17450057]
 [-0.21751369  0.01748088  0.22150462  0.1559105  -0.17450057]
 [ 1.16812909  0.51015372  0.25742689 -0.77396901 -0.17450057]
 [-0.91033509 -0.35695047 -0.40307935 -0.81775835 -0.17450057]
 [ 0.128897   -0.01207949 -0.08789041  0.14174336 -0.17450057]
 [ 1.51453979  0.90429199  0.25510932 -0.89835649 -0.17450057]
 [ 0.4753077   0.41161915  0.05695745 -0.46754666 -0.17450057]
 [ 0.4753077   0.36235187  0.11373781 -0.09062348 -0.17450057]
 [ 0.8217184   0.80575743  0.14618373 -0.42950145 -0.17450057]
 [ 0.4753077   0.54956755  0.14966008  0.13960541 -0.17450057]
 [ 1.16812909 -0.35695047 -0.4668124  -0.89670795 -0.17450057]
 [ 0.4753077   0.43132607  0.31884238  0.36197798 -0.17450057]
 [ 0.4753077   0.55942101  0.26785593 -0.56532568 -0.17450057]
 [ 0.4753077   0.28352422  0.00944735 -0.2819829  -0.17450057]
 [-1.60315648 -0.47519196 -0.04849179  1.04269615 -0.17450057]]


In [23]:
print("The shape of Feature Matrix is -",X_std.shape)

The shape of Feature Matrix is - (301, 5)


In [24]:
X_covariance_matrix = np.cov(X_std.T)

In [25]:
X_covariance_matrix

array([[ 1.00333333,  0.23692812, -0.04774282, -0.52608985, -0.18271057],
       [ 0.23692812,  1.00333333,  0.88191249,  0.02928438, -0.08863858],
       [-0.04774282,  0.88191249,  1.00333333,  0.20432586,  0.00808387],
       [-0.52608985,  0.02928438,  0.20432586,  1.00333333,  0.08951359],
       [-0.18271057, -0.08863858,  0.00808387,  0.08951359,  1.00333333]])

In [26]:
#Compute the eigenvalues and right eigenvectors using np.linalg.eig

eig_vals, eig_vecs = np.linalg.eig(X_covariance_matrix)

In [27]:
print('Eigenvectors \n%s' %eig_vecs)

Eigenvectors 
[[-0.09039584 -0.68032258  0.20273288  0.68159673  0.1526927 ]
 [-0.70076378 -0.10682289 -0.70261671 -0.00443837  0.06187936]
 [-0.6943343   0.11608932  0.68124542 -0.19201495  0.05880546]
 [-0.11847162  0.64665288 -0.00979484  0.69684218 -0.28656511]
 [ 0.06799311  0.30677904 -0.03221618  0.1137868   0.94195448]]


In [28]:
print('\nEigenvalues \n%s' %eig_vals)


Eigenvalues 
[1.92126831 1.63112533 0.07622654 0.4468813  0.94116519]


In [29]:
# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

In [30]:
# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort(key=lambda x: x[0], reverse=True)

In [31]:
#In Python, lambda is a keyword used to define anonymous functions(functions with no name) 
#and that's why they are known as lambda functions

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
1.9212683141209463
1.6311253280544327
0.9411651860766465
0.44688129968587736
0.07622653872876121


In [32]:
tot = sum(eig_vals)

var_exp = [(i / tot)*100 for i in sorted(eig_vals, reverse=True)]
print("Variance captured by each component is \n",var_exp)

Variance captured by each component is 
 [38.29770725822487, 32.514126140619936, 18.760767828770373, 8.907932884103872, 1.5194658882809553]


In [33]:
cum_var_exp = np.cumsum(var_exp)
print ("Cumulative variance captured as we travel each component \n",cum_var_exp)

Cumulative variance captured as we travel each component 
 [ 38.29770726  70.8118334   89.57260123  98.48053411 100.        ]


In [34]:
print("SO WE DROP PC3 AND KEEP PC1 AND PC2 since PC2 captures till 85% of our data")

SO WE DROP PC3 AND KEEP PC1 AND PC2 since PC2 captures till 85% of our data


In [35]:
print("All Eigen Values along with Eigen Vectors")

print(eig_pairs)

All Eigen Values along with Eigen Vectors
[(1.9212683141209463, array([-0.09039584, -0.70076378, -0.6943343 , -0.11847162,  0.06799311])), (1.6311253280544327, array([-0.68032258, -0.10682289,  0.11608932,  0.64665288,  0.30677904])), (0.9411651860766465, array([ 0.1526927 ,  0.06187936,  0.05880546, -0.28656511,  0.94195448])), (0.44688129968587736, array([ 0.68159673, -0.00443837, -0.19201495,  0.69684218,  0.1137868 ])), (0.07622653872876121, array([ 0.20273288, -0.70261671,  0.68124542, -0.00979484, -0.03221618]))]
